[Build] OpenCilk 1.0 RC2 config; cleanup

diff --git a/tools/build b/tools/build
--- a/tools/build
+++ b/tools/build
@@ -1,30 +1,34 @@
 #!/bin/sh
-OPENCILK_SOURCE=/data/Cilk
 
+# Source directory for OpenCilk (root of the opencilk-project repository tree).
+# Must be an absolute pathname.
 case "$1" in
-    /*) OPENCILK_SOURCE="$1"; shift;;
-    -h|-help|--help) echo "Usage: build source-dir build-dir [core count]"; exit 1;;
+    /*) OPENCILK_SOURCE="$1";;
+    -h|-help|--help) echo "USAGE: build source-dir build-dir [core-count]"; exit 1;;
     -*) echo "unknown option $1"; exit 1;;
     *) echo "First argument ($1) must be absolute pathname"; exit 1;;
 esac
 
-# Build director for Tapir.  Currently cheetah has to be built in its
-# source directory.  For the first beta the compiler will not be installed
-# anywhere.  Run it out of ${BUILD_DIR}/bin.
-BUILD_DIR="${1:?}"
+# Build directory for OpenCilk.  Must be an absolute pathname.  The Cheetah
+# runtime has to be built in its source directory, which should be a
+# sub-directory named "cheetah" within the OpenCilk source directory.
+# Similarly, the OpenCilk productivity tools source should be in a sub-directory
+# named "cilktools" within the OpenCilk source directory.  The OpenCilk compiler
+# will not be installed anywhere; run it out of ${BUILD_DIR}/bin.
+case "$2" in
+    /*) BUILD_DIR="$2";;
+    *) echo "Second argument ($2) must be absolute pathname"; exit 1;;
+esac
 
-NCPU="${2}"
-
+NCPU="${3}"
 if test -z "${NCPU}" -a -r /proc/cpuinfo ; then
     NCPU=$(grep -c '^processor' /proc/cpuinfo 2> /dev/null)
 fi
-
 if test -z "${NCPU}" ; then
     if test -x /sbin/sysctl -o -x /usr/sbin/sysctl ; then
     NCPU=$(PATH=${PATH}:/sbin:/usr/sbin sysctl -n hw.ncpu)
     fi
 fi
-
 if test -z "${NCPU}" -o 0 -eq "${NCPU}" ; then
     echo "Unknown CPU count; using 10"
     NCPU=10
@@ -35,8 +39,8 @@ if ! test -d "${OPENCILK_SOURCE}" ; then
     exit 1
 fi
 
-TAPIR_SOURCE="${OPENCILK_SOURCE:?}/opencilk-project"
-CHEETAH_SOURCE="${TAPIR_SOURCE:?}/cheetah"
+CHEETAH_SOURCE="${OPENCILK_SOURCE:?}/cheetah"
+CILKTOOLS_SOURCE="${OPENCILK_SOURCE:?}/cilktools"
 
 exec < /dev/null
 
@@ -52,12 +56,16 @@ OS="$(uname -s)"
 #    *) GMAKE=gmake ;;
 #esac
 
-if ! test -d "${TAPIR_SOURCE}/llvm" ; then
-    echo "LLVM not found at ${TAPIR_SOURCE}/llvm" 1>&2
+if ! test -d "${OPENCILK_SOURCE}/llvm" ; then
+    echo "LLVM not found at ${OPENCILK_SOURCE}/llvm" 1>&2
     exit 1
 fi
 if ! test -d "${CHEETAH_SOURCE}/runtime" ; then
     echo "Cheetah runtime source not found at ${CHEETAH_SOURCE}/runtime" 1>&2
+    exit 1
+fi
+if ! test -d "${CILKTOOLS_SOURCE}" ; then
+    echo "OpenCilk productivity tools source not found at ${CILKTOOLS_SOURCE}" 1>&2
     exit 1
 fi
 
@@ -67,20 +75,20 @@ mkdir -p "${BUILD_DIR}"
 
 cd "${BUILD_DIR}"
 
-COMPONENTS="clang;cheetah"     # Unlikely to change
 : "${OPENCILK_RELEASE:=Release}" # RelWithDebInfo to debug the compiler
 : "${OPENCILK_ASSERTIONS:=On}"   # Off to disable assertions in the compiler
+COMPONENTS="clang;compiler-rt"   # Required components; edit to add extra LLVM projects
 case "${OS}" in
     Darwin)
         : "${LIBCXX:="libcxx;"}" ;;
 esac
-RUNTIMES="${LIBCXX}compiler-rt"
+RUNTIMES="${LIBCXX}cheetah;cilktools" # Required runtimes
+
 cmake -DLLVM_ENABLE_PROJECTS="${COMPONENTS}" \
       -DLLVM_ENABLE_RUNTIMES="${RUNTIMES}" \
-      -DCOMPILER_RT_BUILD_CILKTOOLS=ON \
       -DLLVM_ENABLE_ASSERTIONS="${OPENCILK_ASSERTIONS:?}" \
       -DCMAKE_BUILD_TYPE="${OPENCILK_RELEASE:?}" \
-      "${TAPIR_SOURCE}/llvm"
+      "${OPENCILK_SOURCE}/llvm"
 # Alternatively, make -j "${NCPU}" using the native system make.
 # cmake 3.10 neeeds -- before -j.  cmake 3.16 understands -j
 cmake --build . -- -j "${NCPU}"
